ysapp/urls.py
from django.urls import path
from .views import *

app_name = 'ysapp'
urlpatterns = [
    path('', anasayfa, name="anasayfa"),
    path('restoranlar/', RestoranListView.as_view(), name='restoranlar'),
    path('restoranlar/<int:pk>/', RestoranDetailView.as_view(), name="restorandetay"),
    path('restoranlar/olustur/', RestoranCreateView.as_view(), name="restoranolustur"),
    path('restoranlar/<int:pk>/yemek/', YemekAddView.as_view(), name= 'yemekadd'),
    path('mahalle/', MahalleListView.as_view(), name='mahalle'),
    path('mahalle/yemek/', MahalleAddView.as_view(), name= 'mahalleadd'),

] 

ysproje/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from payment.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ysapp.urls')),
    path('',include('kullanicilar.urls')),
    path('payment/',payment,name='payment'),
    path('ok/', success, name = 'success'),
    path('fail/', fail, name='fail'),
    path('result/', result, name='result'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ysapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Restoran(models.Model):
    kullanici = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    restoranadi = models.CharField(max_length=10000)
    resim =  models.ImageField(upload_to='restoran_images', null= True)


    def __str__(self):
        return self.restoranadi
    
    def get_absolute_url(self):
        return reverse("ysapp:restorandetay", kwargs={"pk": self.pk})
    
    
class Yemek(models.Model):
    restoran = models.ForeignKey(Restoran, related_name="yemek", on_delete=models.CASCADE)
    kullaniciadi = models.CharField(max_length=100, null=True)
    yemekadi = models.TextField(null=True, blank=True)
    resim =  models.ImageField(upload_to='yemek_images', null= True)
    
    def __str__(self):
        return self.yemekadi
    
    def get_absolute_url(self):
        return reverse("ysapp:restorandetay", kwargs={"pk": self.pk})
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

class MahalleYemek(models.Model):
    kullaniciadi = models.CharField(max_length=100, null=True)
    yemekadi = models.TextField(null=True, blank=True)
    resim =  models.ImageField(upload_to='mahalle_images', null= True)
    
    def __str__(self):
        return self.yemekadi
       
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

ysapp/forms.py
from .models import *
from django import forms

class YemekForm(forms.ModelForm):
    
    class Meta:
        model = Yemek
        fields = ["yemekadi","resim"]

        widgets = {
            'yemekadi': forms.Textarea(attrs={'class':'form-control'}),
        }

class MahalleForm(forms.ModelForm):
    
    class Meta:
        model = MahalleYemek
        fields = ["yemekadi","resim"]

        widgets = {
            'yemekadi': forms.Textarea(attrs={'class':'form-control'}),
        }

ysapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView , CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

# Create your views here.

def anasayfa(request):
    return render(request, 'ysapp/anasayfa.html')

class RestoranListView(ListView):
    model = Restoran
    template_name = 'ysapp/restoran_view.html'
    context_object_name = 'restoranlar'
    ordering = ['restoranadi']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ""
        if search_input:
            context['restoranlar'] = context['restoranlar'].filter(restoranadi__icontains = search_input)
            context['search_input'] = search_input
        return context

 

class RestoranDetailView(DetailView):
    model = Restoran
    template_name = 'ysapp/restoran_detay.html'
    context_object_name = 'restorandetay'

class RestoranCreateView(LoginRequiredMixin ,CreateView):
    model = Restoran
    fields = ['restoranadi','resim']
    template_name = 'ysapp/restoran_olustur.html'
    context_object_name = 'restoranolustur'

    def form_valid(self, form):
        form.instance.kullanici = self.request.user
        return super().form_valid(form)
            
    
class YemekAddView(LoginRequiredMixin ,CreateView):
    model = Yemek
    form_class = YemekForm
    template_name = 'ysapp/yemek_add.html'

    def form_valid(self, form):
        restoran_id = self.kwargs.get('pk')  
        restoran = get_object_or_404(Restoran, pk=restoran_id)
        form.instance.restoran = restoran  
        form.instance.kullaniciadi = self.request.user.username  
        return super().form_valid(form)       
    success_url = reverse_lazy('ysapp:restoranlar')

class MahalleListView(ListView):
    model = MahalleYemek
    template_name = 'ysapp/mahalle_view.html'
    context_object_name = 'mahalle'
    ordering = ['yemekadi']

class MahalleAddView(LoginRequiredMixin ,CreateView):
    model = MahalleYemek
    form_class = MahalleForm
    template_name = 'ysapp/mahalle_add.html'
    success_url = reverse_lazy('ysapp:mahalle')

ysapp/templates/ysapp/mahalle_view.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">

    <style>
        body{
            
            font-family: 'Poppins', sans-serif;
            background-color: #e9e4e4; 

        }
        #title-sec {
            display: flex;
            flex-direction: column;
            justify-content: start;
        }

        #title-sec img {
            border-radius: 20px;
            box-shadow: rgba(0, 0, 0, 0.25) 0px 54px 55px, rgba(0, 0, 0, 0.12) 0px -12px 30px, rgba(0, 0, 0, 0.12) 0px 4px 6px, rgba(0, 0, 0, 0.17) 0px 12px 13px, rgba(212, 210, 210, 0.09) 0px -3px 5px;
        }

        #title-sec h3 a {
            text-decoration: none;
            font-size: 2rem;
        }


        .container {
            display: flex;
            flex-direction: column;
            justify-content: start;
        }

        #fh1{
            margin-top: 20px;
            color: black;
            letter-spacing: 3px;
            
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: #EA004B; 

        }

     

        #fh3{
            text-align: left;
            font-size: 19px;
            padding-top: 15px;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 15px;
                text-align: left;
            }
        }
        #fh6{
            text-align: right;
            font-size: 15px;
     
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: right;
                font-weight: normal;
            }
        }
       

        a{
            color: white;
        }
        a:hover{
            text-decoration: none;
            color: #FFC107;
        }
        h5{
            color: rgb(133, 133, 133);
        }

    </style>
</head>
<body>
    <div class="container">
        <div id="sub-nav">
            <h1 id="fh1">Ürünler</h1>
            {% if user.is_authenticated %}
            <button class="btn" id="logout-btn"><a id="fa" href="{% url "ysapp:mahalleadd" %}" style="color: white; text-decoration: none;">Ürün Ekle</a></button>
            {% else %}
            <button class="btn" id="logout-btn"><a id="fa" href="{% url "girisyap" %}" style="color: white; text-decoration: none;">Ürün Ekle</a></button>
            {% endif %}
        </div>
        <div class="yemeklist">
            <div class="yemekler">
                {% for urun in mahalle %}
                <div class="container" style="margin-top: 10px; background: linear-gradient(to right, #EA004B
                , #EA004B
                ); padding: 5px; box-shadow: rgba(0, 0, 0, 0.383) 0px 5px 5px 0px; border-radius: 15px;" >
                    <div id="title-sec" style="display: flex; align-items: center;">
                        <h3 id="fh3"><a href="">{{urun.yemekadi}}</a></h3>
                        <img src="{{ urun.resim.url }}" alt="Mahalle Resim" style="width: 300px; height: 200px;" />
                    </div>
                    <hr>

                </div> <br>
                {% endfor %}
            </div>
        </div>   
    </div>
</body>
</html>
{% endblock content %}

ysapp/templates/ysapp/restoran_detay.html
{% extends 'base.html' %}
{% block content %}


    
   
    <style>

        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        ::-webkit-input-placeholder { /* Chrome/Opera/Safari */
            color: #B5B5B5;
          }
          ::-moz-placeholder { /* Firefox 19+ */
            color: #B5B5B5;
          }
          :-ms-input-placeholder { /* IE 10+ */
            color: #B5B5B5;
          }
          :-moz-placeholder { /* Firefox 18- */
            color: #ccc;
          }
          
          .list {
              height: 100px;
              overflow:auto;
              margin-bottom: 45px;
              }
          .app {
          position: absolute;
          left: 100px;
          bottom: 100px;
          border-radius: 5px;
          max-width: 300px;
          text-align: center;
          z-index:100;
          padding-bottom: 30px;
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.63);
          padding-bottom: 25px;
          overflow: hidden;
          background-color: rgb(255, 255, 255);
          display:none;
          }
          
          .app p {
          color: #838383;
          margin: 4% auto;
          width: 260px;
          padding: 20px;
          }
          
          h2 {
              font-size: 25px;
              padding-bottom: 25px;
              line-height: 0;
              color: #EA004B;
              font-weight: 300;
              padding: 20px;
              padding-top: 40px;
          }
          
          
          .usertitle {
              font-size: 20px;
              padding-bottom: 25px;
              line-height: 0;
              color: #09A7BA;
              font-weight: 300;
              padding: 20px;
              padding-top: 40px;
          }
          
          
          .fa {
              margin-top: 25px;
              color: rgba(0,0,0,0.15);
              font-size: 3em;
          }
          
          .app ul {
              margin-top: 25px;
              padding: 0 20px;
              padding-bottom: 60px;
          }
          
          .app li {
              list-style: none;
              font-size: 1.2rem;
              color: #616161;
              width: 80px;
              display: inline-block;
              overflow: hidden;
          }
          .app li img{
              width: 100%;
          }
          
          .app li:hover {
              color: red;
              cursor: pointer;
              background-color: #efefef;
          }
          
          .app li:after {
              font-family: FontAwesome;
              color: #FFFFFF;
              content: "\f00d";
              margin-left:5px;
              position: absolute;
              display:none;
          }
          
          .app li:hover:after {
              font-family: FontAwesome;
              color: red;
              content: "\f00d";
          }
          
          
          
          button {
              font-weight: 300;
              margin: 20px 0;
              line-height: 2.5rem;	
              font-size: 1.7rem;
              width: 2.5rem;
              background-color: #7A7B7B;
              border: none;
              color: #ffffff;	
              border-radius: 50%;
          }
          
          #send {
              font-weight: 300;
              margin: 20px 0;
              line-height: 2.5rem;	
              font-size: 1.7rem;
              width: 2.5rem;
              font-size: 1rem;
              background-color: #09A7BA;
              border: none;
              color: #ffffff;	
              width: 80%;
              border-radius: 5px;
              cursor: pointer;
            font-weight: 600;
          }
          
          #send:hover {
              background-color: #B6B6B6;
              cursor: pointer;
          }
          
          button:hover {
              background-color: #B6B6B6;
              cursor: pointer;
          }
          
          button:focus {
              outline-width: 0;
          }
          
          #inputshop, #inputname, #inputtel, #inputemail {
              line-height: 2rem;
              font-size: 1.2rem;
              padding: 0 10px;
              border-top: none;
              border-bottom: 1px solid #ccc;
              border-left: none;
              border-right: none;
              background-color: transparent;
              color: #616161;
              text-align: center;
          }
          
          #inputshop:focus, #inputname:focus, #inputtel:focus, #inputemail:focus {
              border-bottom: 1px solid #8888AC;
              outline-width: 0;
              
          }
          
          .items{
          background-color: rgba(255, 255, 255, 0.8);
          border-radius: 5px;
          width: 250px;
          height: 250px;
          text-align: center;
          padding: 60px 0;
          margin: 5px;
          display: inline-block;
              border: 1px solid #ddd;
              vertical-align: middle;
          }
          .items img{
              width: 50%;
          }
          
          .items:hover {
              cursor: pointer;
          box-shadow: 0 0 10px rgba(0,0,0,0.5);
          }
          
          
          #inputname  {
          }
          
          #inputtel {
          margin-bottom: 30px;
          }
          
          
          placeholder {
              text-align:center;
          }
          form {
              text-align:center;
          }
          
          #contactform {
          left: 42%;
          top: 15%;
          position: absolute;
          background-color: #fff;
          width: 306px;
          line-height: 3em;
          margin: auto;
          text-align: center;
          box-shadow: 0 0 10px rgba(141, 141, 141, 0.5);
          border-radius: 5px;
          }
          #contactform p {
          color: #838383;
          }
          
          .closepopup {
          cursor: pointer;
          font-size: 25px;
          width: 20%;
          left: 80%;
          font-size: 16px;
          top: -1%;
          position: relative;
          color: #B9B3B3;
          position: absolute;
          }
          
          .openpopup {
          width: 80%;
          margin: auto;
          font-size: 14px;
          box-shadow: 0 0 5px rgba(134, 134, 134, 0.6);
          background-color: #EA004B;
          border-radius: 5px;
          background-color: #EA004B;
          color:#fff;
          padding: 10px;
          cursor: pointer;
          font-weight: 700;
          transition-duration:1s;
          }
          
          .openpopup a {
            color:#fff;
            text-decoration: none;
          }


          .openpopup2 {
          width: 80%;
          margin: auto;
          font-size: 14px;
          box-shadow: 0 0 5px rgba(134, 134, 134, 0.6);
          background-color: #FFF;
          border-radius: 5px;
          background-color: #797D7E;
          color:#fff;
          padding: 10px;
          margin-top:10px;
          cursor: pointer;
          font-weight: 700;
          transition-duration:1s;
          }
          
          .openpopup1:hover {
          background-color: #09A7BA;
          }
          
          .tooltipshop, .tooltipshop2 {
          color: #fff;
          padding: 5px;
          width: 50%;
          border-radius: 5px;
          background: #db0e0ecc;
          box-shadow: 0 0 10px rgb(141, 141, 141);
          position: absolute;
          width: 160px;
          margin: -15px -90px auto;
          opacity:0;
          }
          
          .tooltipshop:after {
          font-family: FontAwesome;
          color: #fff;
          content: "\f129";
          margin-left: 8px;
          }
          
          .tooltipshop2:after {
          font-family: FontAwesome;
          color: #fff;
          content: "\f129";
          margin-left: 8px;
          }
          
          #tray {
          height:70px;
          width:70px;
          background-color:#EA004B;
          display:block;
          border-radius:50%;
          text-align:center;
          cursor:pointer;
          transition-duration:0.5s;
          position: absolute;
          left: 25px;
          bottom: 25px;
          box-shadow: 0 0 10px rgba(0,0,0,0.5);
          }
          
          #tray:hover {
          box-shadow: 0 0 10px rgb(141, 141, 141);
          }
          
          #tray i {
          color: #ffffff;
          margin-top: 18px;
          font-size: 30px;
          }
          .count {
          position: absolute;
          background-color: rgba(212,7,10,1.00);
          border-radius: 50%;
          width: 22px;
          height: 22px;
          padding: 2px;
          color: #fff;
          font-weight: 300;
          display:none;
          }
          
          .closewindow {
          color: #B5B5B5;
          position: relative;
          float: right;
          left: -3%;
          cursor:pointer;
          width: 20px;
          border-radius: 1000%;
          height: 20px;
          text-align: center;
          margin-top: 5px;
          }
          
          .closewindow span {
              position:relative;
              bottom: 2px;
          }
          
          .items {
            cursor:pointer;
          }
          
          #contactform form {
            padding: 10px;
          }
        body{
            
            font-family: 'Poppins', sans-serif;
            background-color: #e9e4e4;
        }
        #fh1{
            margin-top: 20px;
            color: white;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: #064d13;
          
        }

        .container {
            background-color: #e9e4e4;
            
            padding: 5px;
            
            border-radius: 20px;
        }

        

        #fh3{
            text-align: center;
            font-size: 30px;
            padding-top: 20px;
            text-align: left;
            letter-spacing: 3px;
            color: white;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 17px;
                text-align: left;
            }
        }

        .restoranlist {
            background-color: #e9e4e4;
        }
  


    </style>

    <div class="container">
        <div id="sub-nav">
 
        </div>
        <div class="restoranlist">
            <div class="restoranlar">
                <div class="container" style="background-color: #EA004B
                ; padding: 5px; box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 5px 0px; border-radius: 20px;" >
                    
                    <h3 id="fh3">{{restorandetay.restoranadi}}</h3> 
                    <hr>
                    <img src="{{ restorandetay.resim.url }}" alt="Restoran Resim" style="width: 300px; height: 200px; border-radius: 10px;" />
                    <hr>
                    <h2 style="color:white; font-size:2rem; ">Yemekler</h2> <br><br><br>
                    {% if not restorandetay.yemek.all %}
                    <h3>Henüz bir yemek yok </h3>
                    {% else %}
                    <div id="market">
                    {% for yemek in restorandetay.yemek.all  %}
                    <div class="items product">
                    <h3 style="font-weight:600; font-size:17px;">{{yemek.yemekadi}}</h3>
                    <img src="{{ yemek.resim.url }}" alt="Yemek Resim" style="width: 150px; height: 100px;" />
                    <hr>  
                    </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <br>
                      
                  

                   
                    <a class="btn btn-dark" id="fa" href="{% url "ysapp:yemekadd" restorandetay.id %}" style="text-decoration: none; margin-left: 20px; margin-bottom: 20px;">Yemek Ekle</a>
                    <a style="text-decoration: none;  padding: 6px 50px; margin-bottom: 20px; " class="btn btn-light" href="{% url 'ysapp:restoranlar' %}">&#x21a9;</a>
                </div> <br><br>
                <div class="app">
                    <div class="closewindow">
                    <span>x</span>
                    </div>
                         <h2>Sepetiniz</h2>
                             <i class="fa fa-shopping-basket fa-3x" aria-hidden="true"></i>
                        <p>Sepetinizdeki ürünler:</p>
                      <div class="tooltipshop">Listede yok</div>
                      <div class="tooltipshop2">Önce sepetinize ürün ekleyin!</div>
                         <div class="app-body">
                             <ul class="list"> 			
                             </ul>
                         </div>
                        <div class="openpopup">
                    <a href={% url "payment" %}>Alışverişi Tamamla</a>
                    </div>
                     <div class="openpopup2">
                    Sepeti Boşalt
                    </div>
                     </div>
                      <div class="b-popup" id="popup1">
                        
                     </div>
                      <div id="tray">
                      <div class="count">
                      
                      </div>
                    <i class="fa fa-shopping-basket fa-2x" aria-hidden="true"></i>
                     </div>
                
                </div> <br>
            </div>
        </div>
    </div>
        <br>
        
    
 
        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js'></script>

{% endblock content %}

ysapp/templates/ysapp/restoran_view.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">

    <style>
        body{
            
            font-family: 'Poppins', sans-serif;
            background-color: #e9e4e4; 

        }
        #title-sec {
            display: flex;
            flex-direction: column;
            justify-content: start;
        }

        #title-sec img {
            border-radius: 20px;
            box-shadow: rgba(0, 0, 0, 0.25) 0px 54px 55px, rgba(0, 0, 0, 0.12) 0px -12px 30px, rgba(0, 0, 0, 0.12) 0px 4px 6px, rgba(0, 0, 0, 0.17) 0px 12px 13px, rgba(212, 210, 210, 0.09) 0px -3px 5px;
        }

        #title-sec h3 a {
            text-decoration: none;
            font-size: 2rem;
        }


        .container {
            display: flex;
            flex-direction: column;
            justify-content: start;
        }

        #fh1{
            margin-top: 20px;
            color: black;
            letter-spacing: 3px;
            
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: #EA004B; 

        }

     

        #fh3{
            text-align: left;
            font-size: 19px;
            padding-top: 15px;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 15px;
                text-align: left;
            }
        }
        #fh6{
            text-align: right;
            font-size: 15px;
     
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: right;
                font-weight: normal;
            }
        }
       

        a{
            color: white;
        }
        a:hover{
            text-decoration: none;
            color: #FFC107;
        }
        h5{
            color: rgb(133, 133, 133);
        }

    </style>
</head>
<body>
    <div class="container">
        <div id="sub-nav">
            <h1 id="fh1">Restoranlar</h1>
            {% if user.is_authenticated %}
            <button class="btn" id="logout-btn"><a id="fa" href="{% url "ysapp:restoranolustur" %}" style="color: white; text-decoration: none;">Restoran Oluştur</a></button>
            {% else %}
            <button class="btn" id="logout-btn"><a id="fa" href="{% url "girisyap" %}" style="color: white; text-decoration: none;">Restoran Oluştur</a></button>
            {% endif %}
        </div>
        <div class="restoranlist">
            <div class="restoranlar">
                {% for restoran in restoranlar %}
                <div class="container" style="margin-top: 10px; background: linear-gradient(to right, #EA004B
                , #EA004B
                ); padding: 5px; box-shadow: rgba(0, 0, 0, 0.383) 0px 5px 5px 0px; border-radius: 15px;" >
                    <div id="title-sec" style="display: flex; align-items: center;">
                        <h3 id="fh3"><a href="{% url 'ysapp:restorandetay' pk=restoran.pk %}">{{restoran.restoranadi}}</a></h3>
                        <img src="{{ restoran.resim.url }}" alt="Restoran Resim" style="width: 300px; height: 200px;" />
                    </div>
                    <hr>

                </div> <br>
                {% endfor %}
            </div>
        </div>   
    </div>
</body>
</html>
{% endblock content %}